using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Diceware_Password_Generator
{
    internal class WordsList
    { 
        public int wordCount;
        
        List<string> wordsSplit = new List<string>();

        public WordsList()
        {
            string[] words = 
            { "\r\ndelen\r\ndate\r\ndelstaten\r\nantalet\r\ndecimals\r\nartiklar\r\nbasen\r\narten\r\nbredden\r\ndepartementet\r\ndata\r\nartens\r\ndalar\r\nfor\r\nbaserat\r\nbörjade\r\nan\r\nanvänds\r\nfilmen\r\nfilmer\r\ndivisionen\r\ndelar\r\nartikeln\r\nbör\r\ndelas\r\nalger\r\nbilder\r\narter\r\nboken\r\nanvänder\r\ndagar\r\ndels\r\nbehöver\r\nbetyder\r\nbrukar\r\navled\r\navser\r\narmén\r\nanser\r\nfinalen\r\nbor\r\narbeten\r\nbaserad\r\narbetet\r\narbetar\r\nersattes\r\nbestående\r\nbetydande\r\ndelarna\r\nfallet\r\nartister\r\nbilden\r\nformer\r\nanvändaren\r\nalfabetisk\r\nfort\r\nbetydligt\r\nanvänts\r\negenskaper\r\nbromsar\r\nbildar\r\ndikter\r\nbeskriver\r\navsnittet\r\nberor\r\narts\r\nens\r\nfaktiskt\r\nbyggd\r\nberättar\r\nbildas\r\nfadern\r\nbebyggelsen\r\nbytes\r\nalls\r\nbetydelser\r\narbetat\r\nfigurer\r\ndagbladet\r\nbröt\r\nanger\r\nbarnen\r\nbevarade\r\nfalls\r\nefterträddes\r\nformen\r\ndriver\r\nberömda\r\nbilen\r\narkitekter\r\ndelades\r\nbanks\r\nartikelns\r\nefterträdde\r\nbehåll\r\nbon\r\nelever\r\nbilar\r\nfolket\r\nenheter\r\nberättelser\r\nanvänt\r\nbesökte" +
              "\r\narkitekten\r\nformellt\r\nfaller\r\nbron\r\nfolkets\r\nanslöt\r\nbyggt\r\ndanske\r\nbetydelsen\r\nbyggas\r\ndelade\r\nadministrativt\r\nenkla\r\nbarnet\r\nantyder\r\nblommor\r\naktivt\r\nalternativt\r\ndör\r\nbildat\r\nberättelsen\r\nbodens\r\nbeteckningen\r\nbosatte\r\nflyttar\r\narenan\r\namerikanskt\r\nbibeln\r\ndottern\r\nbenämningen\r\nflygplanet\r\nbergs\r\ndyker\r\nflickor\r\nbedrev\r\nbelönades\r\nbeslutet\r\nfaderns\r\narméns\r\nbruket\r\ndödades\r\narkiverat\r\nbröder\r\nbyggts\r\nfilmens\r\ndomstolen\r\nforna\r\nfelaktigt\r\nbart\r\nbildandet\r\nankan\r\nbyggandet\r\nböckers\r\ndjupt\r\nbenämns\r\neditors\r\nextremt\r\nansvaret\r\nanvänd\r\ndöptes\r\nbestämt\r\nbelägna\r\nbrodern\r\nberättade\r\nbryter\r\nflyttat\r\navdelningen\r\ndebatten\r\navrättades\r\nbaseras\r\nalfabetet\r\ndelad\r\nbesöker\r\nfiske\r\nbyggs\r\nantikens\r\nefternamnet\r\nfasaden\r\ncentralt\r\ndags\r\ndikten\r\nblandad\r\nbranden\r\narms\r\nbehovet\r\nflickan\r\nantiken\r\ndödade\r\nbollen\r\nanta\r\nbevarad\r\nbesökt\r\nbola\r\nanvändarnamn\r\nbedöms\r\nding\r\nevent\r\nekonomin\r\nansökan" +
              "\r\navhandlingen\r\navrättade\r\ndefinitivt\r\ndelstatens\r\nbanor\r\nblandade\r\nflyter\r\nbladen\r\nberodde\r\nanvändningen\r\nbildats\r\nbacken\r\neffekten\r\nbruna\r\nbros\r\neffektivt\r\ndelstater\r\nadelns\r\nelektronisk\r\nartisten\r\nadeln\r\nansiktet\r\nenheten\r\nbeslutar\r\navsevärt\r\nbokstaven\r\nbosatta\r\nfiras\r\neden\r\nbegränsat\r\nande\r\ndubbelt\r\nbröts\r\navtalet\r\nbeskrivas\r\nblodet\r\nbenen\r\navsett\r\naltaret\r\nblott\r\netablerat\r\nensamma\r\nersättas\r\nfirman\r\nbaden\r\nbefälet\r\nblommorna\r\nfiler\r\nbelägringen\r\nanor\r\nbenämnd\r\nbuken\r\nandelen\r\nbars\r\nfarfars\r\nfokuserar\r\nenorma\r\nbitar\r\ndagars\r\ndatorn\r\nartists\r\ndelat\r\nberör\r\nbarnens\r\ndylikt\r\nbussar\r\nfalska\r\ndömd\r\nanimerad\r\nelden\r\nemiratet\r\nbegärde\r\nbuskar\r\nbäste\r\nbeskrivits\r\ndraken\r\neleven\r\navancerad\r\ndalen\r\nbrändes\r\nekar\r\nanvändarens\r\nbevarat\r\nblandas\r\nevents\r\ncentralorten\r\ndefinitionen\r\nambassaden\r\navslutat\r\nbetraktar\r\nbehandlingen\r\ndeltävlingen\r\narkeologer\r\nanfallet\r\nbesegrat\r\nfilologer\r\navdelningar" +
              "\r\nansetts\r\nfiguren\r\ndanskt\r\nfine\r\nfortet\r\nbrutit\r\nforms\r\nanföll\r\nbasisten\r\netappen\r\ndagbladets\r\ndomaren\r\nbokens\r\ndörrar\r\narbetarna\r\nburks\r\nakademin\r\nanvändarna\r\navbröts\r\nflyttats\r\ndörren\r\navslutar\r\ndanser\r\navsnitten\r\nalbumen\r\nberättas\r\nbilarna\r\nfilms\r\ndagligt\r\napoteket\r\nbarns\r\nfirar\r\nbedrevs\r\nbevarats\r\ndigitalt\r\ndebuten\r\nanpassad\r\nalle\r\naktörer\r\nbranta\r\nformeln\r\narmar\r\nbeslutat\r\navrättad\r\nbröstet\r\nformatet\r\nflygplanen\r\ndateras\r\nadressen\r\narkivet\r\ndirigenter\r\nbaksidan\r\ndöds\r\nbands\r\nberäkningar\r\nbestäms\r\nals\r\nbyten\r\nbeskrivit\r\ndimensioner\r\ndeltävling\r\ndams\r\ndomkyrkan\r\ndammen\r\nfiskare\r\ndansen\r\ndansar\r\nbackar\r\narenor\r\nfisken\r\nbränder\r\nberörda\r\nflygeln\r\nflygningen\r\ndefinitioner\r\nfilosofin\r\ncovers\r\nfinskt\r\nblandar\r\nbytet\r\nenergin\r\nansökte\r\nanalyser\r\narmen\r\namerikanen\r\navgränsar\r\nberömde\r\nenormt\r\nadlad\r\nbordet\r\namerikaner\r\narvet\r\nbonden\r\nanstalten\r\navbröt\r\ndöms\r\nbarnets\r\ndelats\r\neuropeiskt\r\nbeger" +
              "\r\nevigt\r\narkiverad\r\nbygden\r\nbong\r\ndomstolar\r\ndammar\r\nbevaras\r\nfolken\r\nbrunt\r\nedets\r\nbefästningar\r\nfattar\r\nfelet\r\ndistansen\r\nbjörnen\r\ndemoner\r\nberättat\r\ncyklar\r\nbehövas\r\nelektriskt\r\nfilosofisk\r\ndyra\r\nassists\r\ncentern\r\nanvändares\r\ndeltävlingar\r\ndrivit\r\nfonden\r\nbaletten\r\nbärande\r\nelektroner\r\narkeologisk\r\nbenet\r\netiska\r\nbenämnt\r\nbilolycka\r\nfjällen\r\nbaserar\r\nfilen\r\nbarren\r\nbesatt\r\navstängd\r\nandar\r\nbedömningen\r\nblomman\r\nfester\r\nbetalas\r\nenas\r\nelementen\r\nbekräftar\r\nbosätta\r\nanden\r\nbokmässan\r\nbrände\r\nfasen\r\nfarmors\r\ndramer\r\nantologin\r\neditions\r\nfalskt\r\nbaser\r\nfesten\r\nboten\r\nexisterat\r\nanat\r\napor\r\ndebatter\r\neuron\r\nfirandet\r\nbataljonen\r\nberömt\r\nfiskarna\r\negenskapen\r\nbetonar\r\nbesläktat\r\nbesöktes\r\nbarken\r\navrättningen\r\nepisoder\r\ndesignen\r\naxeln\r\narvingar\r\ndamen\r\neran\r\nforntiden\r\nbekräftat\r\natomer\r\nfaser\r\ncitrus\r\naposteln\r\nbegränsar\r\nakten\r\nelefanter\r\navsiktligt\r\nflyglar\r\navgöras\r\ndömts\r\nbolagen\r\nfansen" +
              "\r\nbundna\r\nbussen\r\nallas\r\navancerat\r\nbrukas\r\nfarmer\r\nbrandstation\r\nfinare\r\nforskaren\r\navsatte\r\nanpassat\r\nagenter\r\ndaterat\r\naraber\r\nannans\r\nadresser\r\nansett\r\ndals\r\narbetets\r\nbanorna\r\ndrakar\r\nefterträds\r\navrättas\r\nbergens\r\nambassader\r\nagerat\r\nbilens\r\ndyrt\r\nblanka\r\naspen\r\nbörsen\r\narga\r\nels\r\ndelegationen\r\ndecimaler\r\nbeter\r\nfolks\r\navgifter\r\nenhetligt\r\nfederalt\r\nbiskoparna\r\navvikelser\r\nenhälligt\r\nambitioner\r\nbibelns\r\nfisket\r\nalbaner\r\namatörer\r\nelektroniskt\r\nfinkar\r\narkeologen\r\nbeslöts\r\nantagandet\r\nbadet\r\nfarten\r\ncivilt\r\nekologisk\r\nanas\r\nblomstrade\r\ndelegater\r\nfantastisk\r\ncirkeln\r\nansikten\r\nbanans\r\nbäras\r\ndragen\r\nbesegras\r\narealen\r\nbesöks\r\nbygg\r\nbollar\r\nanslöts\r\nbesökta\r\naktioner\r\nburras\r\nbrända\r\neliten\r\nfantastiskt\r\navslutats\r\nantenner\r\nbefäst\r\nbasinkomst\r\ndelningen\r\narmarna\r\nfaran\r\ncitatet\r\netiketten\r\nbilmärken\r\nbevakar\r\nelefanten\r\ndansade\r\nankomsten\r\nepoken\r\nbönor\r\nexistensen\r\nberättaren\r\nbakbenen" +
              "\r\nböner\r\nberättande\r\nfaders\r\ners\r\nbehandlingar\r\nfiktivt\r\nelements\r\nbladet\r\ndrivers\r\navrättningar\r\nfinländskt\r\nambitionen\r\nanalysen\r\nflygfältet\r\ndrivas\r\nbegärt\r\namiralen\r\nbelagda\r\nanlänt\r\nanslutit\r\nante\r\nanläggas\r\nbarks\r\nbrukligt\r\ncykeln\r\nblekt\r\nerotiska\r\nfiskarter\r\nblixten\r\nborden\r\nboxen\r\ndesignat\r\narbetarnas\r\ndanskar\r\nbildens\r\nfonder\r\nfilmatiseringen\r\nbördiga\r\nbesöket\r\nbetraktats\r\ndaterats\r\ndeltagaren\r\naveln\r\nbilligt\r\nblandningen\r\nentydigt\r\navlägset\r\nbeskrivet\r\ndefinitions\r\nbevisat\r\nanvändarnamnet\r\nbusk\r\nelementet\r\nfattat\r\nbetalat\r\nböjs\r\nbrukets\r\nangivet\r\nallén\r\ndirigenten\r\nartefakter\r\nanmält\r\nbeklagar\r\nanklagas\r\navgränsat\r\nforsar\r\ncyber\r\nanlagda\r\ndomstolens\r\nfjället\r\nfontänen\r\nadels\r\nbalansen\r\ndrakens\r\nberäknats\r\nfinnes\r\nanklagats\r\nbäckar\r\nbelönats\r\ncivilrätt\r\navatar\r\nböjd\r\nbrutalt\r\navvisar\r\nbrödet\r\nfaror\r\nbrands\r\nagar\r\ncirklar\r\ndumt\r\naudition\r\napan\r\nbrutet\r\nberäknat\r\nfaktorn\r\nbusstrafik\r\nfolkligt" +
              "\r\nbjörnar\r\nbotar\r\nbrutits\r\nfilosofins\r\ndates\r\nbeviset\r\nbeskedet\r\nbilmodeller\r\nbevarades\r\narken\r\nartistisk\r\nbelyser\r\nbeträffar\r\nflaskor\r\nflygplanets\r\neken\r\nberäknar\r\nalver\r\nepoker\r\netablerats\r\nbränd\r\nbarometern\r\nbönen\r\ndräktighet\r\ndöparen\r\nalpen\r\nflyglarna\r\nekonomer\r\netableras\r\nfinanser\r\nanslutningen\r\nanlagts\r\nbesökaren\r\nbevisar\r\nbebyggas\r\ndansande\r\ndiken\r\nalgoritmer\r\narkeologiskt\r\ndelfiner\r\nfokuserat\r\nbasilikan\r\nbittra\r\nbroderns\r\nensidigt\r\nfils\r\nbaren\r\nbelönas\r\nanfölls\r\nandligt\r\nbevarar\r\nanmälaren\r\nakademins\r\nflygtiden\r\nborgerligt\r\ndistanser\r\nbildarkivet\r\ndrivits\r\nbelönade\r\nekologiskt\r\nbina\r\nbedömts\r\napotekaren\r\nfotbolls\r\nbullen\r\nanalogt\r\ndjurs\r\nbakar\r\naktern\r\nblandades\r\ndamsingel\r\nbruden\r\nbjörkar\r\ndegen\r\nbokhandeln\r\ndepartementen\r\nfares\r\nepisoden\r\nenar\r\nexternt\r\nformulerat\r\navfyras\r\nciterat\r\nalfabetiskt\r\naningen\r\navläst\r\naromatiska\r\nciteras\r\nbelönad\r\ndigitaliserad\r\nberörs\r\nbiton\r\negentligt\r\nandelar" +
              "\r\nforntidens\r\nfinesser\r\nfilosofiskt\r\nbrännas\r\nfanan\r\nbränns\r\nepitetet\r\nbagare\r\nalbans\r\nbevarandet\r\nbetalda\r\nbeställt\r\nflugan\r\nbaletter\r\nfattigt\r\nenat\r\nbiter\r\nbägaren\r\nenergiskt\r\nbränt\r\nfinnar\r\nballa\r\nfingers\r\nformuleras\r\nautonomt\r\nantropologer\r\nambitiösa\r\naskan\r\nbesegrats\r\nduken\r\ndubbning\r\navvaktar\r\nbekräftats\r\nfalken\r\navkommor\r\nfaras\r\ndansaren\r\nbetar\r\nandan\r\nblomningen\r\nforums\r\nfanor\r\nanmäl\r\nalkoholer\r\nbadhuset\r\ndeltagandet\r\nfolkens\r\nfenor\r\ndivisions\r\nagenten\r\nblandningar\r\nbefolkat\r\naktionen\r\nanslutet\r\nbekräftad\r\ndubbel-cd\r\nbordat\r\nbeslutas\r\nbitch\r\navgiften\r\ndruvan\r\nberäkningen\r\nelektorer\r\nfonetiska\r\nanpassats\r\nbudet\r\nfeta\r\nbetonas\r\nbanvallen\r\nbevisen\r\nbotanikern\r\nflaskan\r\nbesvarade\r\navis\r\nfinals\r\nartikels\r\nfilantroper\r\nbundet\r\ndelfinen\r\narma\r\nbaronen\r\ncenters\r\nbebyggd\r\ndiktens\r\nduvan\r\ndimensionen\r\nanar\r\nberättigad\r\nalar\r\nanpassar\r\nbolas\r\nforsen\r\ndömt\r\ndebattörer\r\nbalanserad\r\ndroppar\r\nbetjänar" +
              "\r\nformationer\r\nbefästningen\r\ndalens\r\navgjorts\r\nbygdens\r\nfonologi\r\nfordringar\r\nandens\r\nfinessen\r\nformats\r\nbarons\r\ndist\r\nfabler\r\nbeläggas\r\nfastighets\r\nanmäld\r\navkastningen\r\nflygbasen\r\ncitadellet\r\nballast\r\ndagboken\r\nbuse\r\navrättats\r\ndemonen\r\navsatts\r\navlöstes\r\nblodigt\r\nblinde\r\neftergifter\r\narmerad\r\ndigital-tv\r\nbruken\r\navkomman\r\nbitarna\r\nautentiska\r\nbojan\r\ndatorns\r\neftersträvar\r\nfastan\r\nbetald\r\ndekorativt\r\nflygtrafik\r\nbetecknad\r\nbesvärande\r\ndubbad\r\nbackarna\r\nfetter\r\nfelen\r\nbalen\r\navbildat\r\nbalkar\r\ndivisionens\r\navhängiga\r\narkitekters\r\nekon\r\ndemons\r\nfinske\r\nblodets\r\nalpint\r\nefterföljd\r\ndesigners\r\nbesattes\r\nbindningar\r\narkiven\r\narresteras\r\nefterlämnat\r\navbildningen\r\nbulan\r\nanatomer\r\ndatan\r\navgjord\r\nfilmats\r\nansluts\r\nanför\r\nbänkarna\r\nberott\r\narguments\r\nbenämnts\r\nbasers\r\nbetraktat\r\nbjörken\r\nderivatan\r\nansökt\r\ndimman\r\narkiveras\r\nbuda\r\nefterord\r\nflygbaser\r\nbesvarar\r\ndotters\r\nbrukat\r\naven\r\navena\r\ncykler\r\nbältet" +
              "\r\nekonomen\r\nberättad\r\nbira\r\navgörandet\r\ndekorerat\r\nansöker\r\ndomkyrkans\r\nbildningen\r\nbossa\r\nanklagat\r\nbekände\r\nbefästes\r\nfickan\r\nfabriks\r\navträddes\r\nfiskaren\r\nbiltrafik\r\negenhändigt\r\nbushs\r\nblazers\r\nbeställd\r\navrustad\r\nforts\r\nbrottarna\r\nangivits\r\nbassängen\r\ncylindern\r\nbelgaren\r\nantikt\r\nfokuserad\r\nbys\r\nbetoningen\r\nbodarna\r\nbefintligt\r\nforskargrupp\r\nbäraren\r\nbaronessan\r\narenans\r\narenorna\r\nbäddar\r\nbelastningen\r\ndaten\r\ndens\r\nfinne\r\netiken\r\nbevakas\r\nappen\r\nbedömt\r\nbödeln\r\nbekvämt\r\nanvändarkonton\r\nfiskeby\r\nfirmans\r\nbevisats\r\nartiklars\r\ndonerat\r\ndöparens\r\nbits\r\nballads\r\nberber\r\nbyggen\r\nefterlyser\r\ndomprosten\r\nberättelsens\r\narkeologin\r\nbygder\r\nbangs\r\navsatta\r\ndukar\r\nfordrar\r\ndomprostar\r\nbehagar\r\nbilmärket\r\nbären\r\nbakas\r\nfarmen\r\nbuds\r\nangränsar\r\nangelägna\r\nbesvaras\r\nblocks\r\nbelades\r\nalmar\r\nfantasin\r\nbebyggt\r\neposet\r\navträdde\r\nbotaniken\r\nagents\r\nenväldet\r\nbegärd\r\nberörd\r\nblixtar\r\nbinärt\r\naspar\r\nfenorna\r\nalps" +
              "\r\netiskt\r\ndepartementets\r\nbefogat\r\ndubbeln\r\nenvist\r\nfasadens\r\ndotterns\r\nbäckenet\r\narme\r\navlats\r\nelastiska\r\ndomänen\r\nbettet\r\ndimensions\r\ndesignern\r\nbeslutats\r\navlas\r\navsändaren\r\ndars\r\nbekväma\r\ndiktverk\r\nantropomorfa\r\nefterliknar\r\navkomlingar\r\nbastionen\r\nbebor\r\nbakaxeln\r\nedens\r\nbassänger\r\nburs\r\nappar\r\nfartygs\r\nformationen\r\nanvändarnas\r\ncheckers\r\ndansens\r\navsättas\r\nfarmers\r\natlant\r\nansträngd\r\nalgoritmen\r\ncigarrer\r\nartisters\r\nfirmor\r\nbybor\r\nfalangen\r\nflickans\r\navsnittets\r\nandningen\r\nbetalningen\r\nbetjänas\r\nelen\r\nbestämmelsen\r\nanlitar\r\netnologer\r\narbetares\r\nadligt\r\nbrukats\r\naboriginer\r\nbränts\r\nbankiren\r\nanlitat\r\nblankt\r\nbocken\r\nflackt\r\nflygplanstypen\r\nbelgiskt\r\ndekoren\r\nanlitats\r\nekorren\r\nfiskevatten\r\nasken\r\ndubbelseger\r\navlat\r\nbekymrad\r\ndubbar\r\nenats\r\nanställs\r\nbrösten\r\ncents\r\narsenals\r\navfallet\r\neftersökt\r\nenad\r\nbesätta\r\naktören\r\navtalen\r\ndinar\r\nbarrens\r\nbetingelser\r\nfiskars\r\nantisemitisk\r\nfogas\r\neras\r\narmémuseum" +
              "\r\nbittert\r\ndatumen\r\nfiskas\r\nbakkant\r\nbetonat\r\nbites\r\navrundat\r\nankor\r\ndroppe\r\nfestivals\r\nblandats\r\nbestämts\r\nbanat\r\navföringen\r\ndrivet\r\navvisat\r\nalkoholen\r\ncancern\r\ncentimeters\r\nflickors\r\nbörjades\r\nbetonad\r\nbossen\r\nbeser\r\nfala\r\nbesökas\r\nenhetens\r\nfarsen\r\nanfört\r\nbodega\r\nbogen\r\nagerandet\r\nadderas\r\nbastioner\r\nbladens\r\nfattats\r\nartistens\r\nbarden\r\nelevens\r\nfonds\r\nborgaren\r\nbunkern\r\nfiskefartyg\r\nbensen\r\nansamlas\r\nforten\r\nbaracker\r\ndiket\r\nbildelar\r\nenfärgat\r\ndrömt\r\ndoriska\r\nfebern\r\nanordningen\r\nbaserna\r\nflygtrafiken\r\nadlats\r\nbeläggen\r\nbörser\r\ndevisen\r\nfettet\r\nbemöttes\r\nbotas\r\nambassadens\r\nfiskarnas\r\nantropologen\r\nfalkar\r\neldens\r\nbiltrafiken\r\nbojor\r\ndebatteras\r\nbeställas\r\nbrudar\r\ndettas\r\nfems\r\nbronsstaty\r\narters\r\nankaret\r\nbräder\r\nflygmotorer\r\nbestämningar\r\nalsters\r\ndomslutet\r\nbemött\r\nfokuset\r\nbeställer\r\nbens\r\nbaltisk\r\nanmälas\r\nbruksort\r\nbokhandlaren\r\nfirat\r\nfortets\r\nanatomin\r\nantikommunism\r\nfiskens\r\nbalanserar" +
              "\r\nfaserna\r\nbananen\r\nflygs\r\nbaler\r\narrendet\r\nansvarat\r\nanställt\r\nbrudens\r\nbikupan\r\naraben\r\nbokade\r\nalen\r\nbastun\r\nbetongen\r\nbusken\r\nfenoler\r\nbetygen\r\nelektronen\r\nberättades\r\nbortamål\r\nank\r\nbelägringar\r\nfogar\r\nantennen\r\nblomstertid\r\nfondens\r\neftersökta\r\navböjt\r\navancerar\r\netern\r\nelmotorer\r\nbords\r\ncirkelns\r\nalbanskt\r\nagendan\r\neftersträvas\r\nbokar\r\nantiloper\r\nefterföljs\r\narsenalen\r\nblommornas\r\nflygbolagen\r\nallans\r\nelastiskt\r\nbeställaren\r\nbilmodellen\r\ndelegationer\r\nchecklista\r\nbrevväxlingen\r\nbaksätet\r\ndödandet\r\nbankirer\r\nelakt\r\nefterspelet\r\ndigitalkameror\r\nblommans\r\nderivator\r\ndisken\r\nbehagligt\r\nanmäls\r\nbetett\r\nberört\r\narresterats\r\nbesköt\r\nanammat\r\ndesigns\r\navvikelsen\r\nbränderna\r\navklarat\r\nandarna\r\nemotions\r\nbalar\r\nemiren\r\ndebatterats\r\navlagda\r\nfenan\r\nbrottaren\r\ndesignar\r\ndansat\r\nautentiskt\r\ncitaten\r\nbalanserat\r\nerat\r\nfarser\r\nbeklagligt\r\ndrinken\r\naktens\r\nbolags\r\negenmäktigt\r\nfigurens\r\nemotionellt\r\natomen\r\nberövade" +
              "\r\nformaten\r\nbifölls\r\ndansösen\r\nalbatrosser\r\ndyre\r\narmadan\r\nenes\r\nblint\r\nbildningar\r\ndroppen\r\ndonerats\r\ndinas\r\nansträngt\r\nberättigat\r\nforskares\r\nbeställts\r\nbagaren\r\nfarter\r\nbesvären\r\nbondens\r\ncenterns\r\navlönade\r\ndelbart\r\nfilologen\r\nblont\r\nbindningen\r\narketyper\r\nbadorten\r\navstannat\r\nbaskisk\r\nbesväret\r\nbetalats\r\ndiminutiv\r\nansatser\r\neditioner\r\nbedragaren\r\nbrune\r\ndeformeras\r\nböjt\r\nbävern\r\nfasor\r\nbunkers\r\nbons\r\nanalytiskt\r\nbastar\r\nbossar\r\nanförs\r\nbifigurer\r\nepidemin\r\nberett\r\nbelastas\r\nbaserats\r\nbrädan\r\nbilmekaniker\r\navgaser\r\nbebyggelsens\r\nbevakat\r\nformens\r\ndonerar\r\ndrives\r\neldas\r\ndividerat\r\nbildligt\r\ndekoreras\r\navfarten\r\nanställas\r\nbrädet\r\nanföranden\r\narvingen\r\ndeltat\r\nbonusar\r\ndagvatten\r\nfiltar\r\nbreddats\r\nbullar\r\nbrevbäraren\r\nfonetiskt\r\nbetet\r\navbildats\r\nalfabetets\r\nagenterna\r\nelevers\r\nburar\r\nbarret\r\nbevingad\r\nbranter\r\nbasfakta\r\nanoden\r\nbetitlat\r\nfalks\r\ndetonerar\r\ndiagonalen\r\narkitektens\r\ndarts\r\netologi\r\nbegärs" +
              "\r\naktad\r\nbakdelen\r\nbotens\r\nbetänkandet\r\nfalske\r\nbotaniskt\r\nbakdel\r\nfiskade\r\nbrunns\r\nberättandet\r\ndirigerat\r\nbilateralt\r\nburken\r\nbarkas\r\nanförts\r\ncharmerande\r\nbländande\r\neremiten\r\nfarms\r\napatiska\r\nenkäten\r\nbesvarades\r\nanmälts\r\ndansades\r\nenklaven\r\nbarbarer\r\nbilan\r\nekumeniskt\r\nbards\r\navskaffar\r\nbönhus\r\nflygtimmar\r\nbaspar\r\navslagen\r\nbonar\r\nberövades\r\nalms\r\nfläsket\r\nbitas\r\nantänds\r\nanställts\r\nantropologin\r\nbesökts\r\ndonatorn\r\nflickas\r\nanestesi\r\nbilds\r\nbevakad\r\nbetaversion\r\nfokuseras\r\nbesköts\r\nfinalens\r\ncykelvägar\r\nbokhandelns\r\nartigt\r\navlönad\r\ncykliskt\r\nbakkanten\r\nbilister\r\nbetas\r\nfarorna\r\nanbudet\r\narbetstiden\r\nbultar\r\netnologisk\r\nbaroner\r\nagile\r\nbeständigt\r\ndelrepublik\r\navsatser\r\ndedicerad\r\nbiskoparnas\r\navstängt\r\nentropin\r\ndamligan\r\nauditions\r\ndramats\r\nbesten\r\nboven\r\nbranten\r\nanföras\r\ndubbelmötet\r\nanträdde\r\nformulerats\r\nekonomins\r\nbogseras\r\nerotiskt\r\nbanvallar\r\nefternamnen\r\nantagonisten\r\netyder\r\nbevingat\r\napoteken\r\nbetingar" +
              "\r\navbrutits\r\nbarnbarns\r\nbereds\r\nbefaras\r\nasymmetriskt\r\nbarrs\r\nbelägrar\r\nbeskattningen\r\nagas\r\nbemöts\r\naxels\r\nensamme\r\nandranamn\r\nbiblioteks\r\narkaden\r\namatörmusiker\r\nbokskogar\r\nbalanseras\r\nborna\r\ndonerad\r\nchefs\r\nbelägrat\r\nbedömd\r\nfirats\r\nfarsan\r\ndubbat\r\nfiskenät\r\ndutta\r\nbelönar\r\navbrutet\r\nbetingat\r\nbrevskrivare\r\nbakfoten\r\ndukas\r\nbasketlag\r\navdelningens\r\nfatet\r\nbärarens\r\nfirad\r\nbestyckat\r\nbiljetten\r\nalternerar\r\ndarras\r\natomenergi\r\ndigitaliserat\r\nasfalten\r\narmeniskt\r\nbadanläggning\r\narbetarens\r\nbelägrad\r\n\r\nbekostat\r\nanslagen\r\ndebattören\r\nbepansrat\r\nbakvänt\r\nelektronens\r\nerinran\r\nanrik\r\nbadade\r\nbuntar\r\nbaken\r\nbesvarat\r\napotekets\r\nbataljonens\r\nflygmotor\r\navskedet\r\nelektroden\r\nbarbaren\r\nbartendern\r\nansar\r\nbotade\r\nciterats\r\navbrutit\r\ndeckaren\r\nforskarlag\r\nflutit\r\ncheckar\r\nblöder\r\nbokföringen\r\nanropet\r\ndekadens\r\nbesvikelsen\r\neventet\r\nbrukad\r\nensitsigt\r\ndetektorn\r\nfasades\r\naktas\r\nbeläggs\r\nansatta\r\nfläktar\r\ncirkulationen\r\nanimaliskt" +
              "\r\navtalat\r\nbisatser\r\nbottenplanet\r\nexperts\r\nbackas\r\nbilagan\r\nbangatan\r\nbilades\r\nadderar\r\nchecker\r\nakademikers\r\ndagblads\r\nbesöken\r\ndebatterat\r\nfaste\r\nbanketten\r\nenväldets\r\nansatsen\r\nbromsning\r\nbördan\r\navvisats\r\nagendor\r\ndrapan\r\nbelastar\r\navfärdat\r\nelementens\r\nansiktets\r\nbitars\r\nagnar\r\ncovern\r\navfärden\r\nbemanningen\r\nbarnavård\r\nbesvarad\r\narkiverar\r\nbrokigt\r\nbalken\r\nanors\r\nbandylag\r\neuropén\r\ndesertörer\r\nbenens\r\nenväldigt\r\nbönorna\r\nfantastik\r\ndomarens\r\neländet\r\nböne\r\nbulten\r\nbuden\r\nbördigt\r\nbärgas\r\nbokskogen\r\ndecimalt\r\nekots\r\nbögar\r\nbalettens\r\nbjörnens\r\nekens\r\nanfalls\r\nbackens\r\nagenturen\r\navstannar\r\nfalkens\r\navlöser\r\nbefälen\r\netnologen\r\nberättarkonst\r\navlett\r\nbelagts\r\nbefolknings\r\nfarc\r\nburet\r\narmens\r\nackumuleras\r\navverkningen\r\ndins\r\nberättarens\r\nbadkaret\r\nanimerat\r\nbegränsats\r\ndrickas\r\nbönan\r\nalkan\r\namuletter\r\nfiskehamnen\r\nfete\r\nelefantens\r\nbiföll\r\nalkemisten\r\nbestämningen\r\navslutet\r\nfilters\r\nefterrätter\r\nbukens\r\nenigt" +
              "\r\nfilologisk\r\nekers\r\navdelades\r\nerosionen\r\nbidar\r\nbladets\r\nbilderboken\r\nbors\r\nbarnamord\r\neuropes\r\naltarets\r\nfilformatet\r\navfärdats\r\navlöst\r\nfansens\r\ncykeltrafik\r\nandarnas\r\nbaronens\r\navtalets\r\nbasens\r\ndeponeras\r\nformuläret\r\nfesterna\r\ndialektiska\r\nansiktena\r\nbakat\r\nblomfluga\r\navböjd\r\naprils\r\nepilogen\r\ndeponerad\r\nfilantropi\r\nefterklang\r\nfeminint\r\nallegoriskt\r\ncampingen\r\nbordellen\r\nberättats\r\ndilemmat\r\nagan\r\nborras\r\nbränningar\r\nbröders\r\nensligt\r\nbrasan\r\nbreddat\r\nbromsen\r\nbakverket\r\nbogens\r\nbitit\r\nalkemister\r\nanfadern\r\nadelskapet\r\ndators\r\nfiktionen\r\nboks\r\nbemötts\r\nformations\r\ndelmoment\r\nanlöper\r\navskräcker\r\nflygplanens\r\nduster\r\nbrännaren\r\nepokens\r\navdelade\r\nbolagens\r\nfalsen\r\navtryckaren\r\nbisarrt\r\nfilologin\r\nbilvägen\r\nantropologisk\r\nbroders\r\natoms\r\nbegäret\r\nbebyggts\r\nbakelser\r\nfibern\r\nefsa\r\navskedats\r\ndoneras\r\ncykellopp\r\naxen\r\ndiskursen\r\nakademikern\r\ndanas\r\nbodegas\r\nbäddade\r\nansatte\r\nallesammans\r\narbetats\r\nbasaren\r\ndesignats" +
              "\r\ndermatolog\r\navverkat\r\nanständigt\r\nabnorma\r\nfantasins\r\nepiskt\r\nanstaltens\r\nantroposofisk\r\ndeterministisk\r\ndigra\r\nbifogas\r\nbelastad\r\nenslingen\r\nflygas\r\nbilismen\r\narbetspendling\r\nassistens\r\nchokladfabrik\r\nblött\r\nbelägras\r\nflygresor\r\ndekorerats\r\nbakluckan\r\nagonis\r\nemissions\r\ndovt\r\nfilens\r\nbreds\r\nflygödlor\r\ncharterbolag\r\nflickkör\r\ndoms\r\nantifascism\r\nbeskylls\r\nekologin\r\nfallens\r\nfogat\r\nanimations\r\nbäres\r\navleds\r\nbrännbart\r\nformateras\r\ndiftongen\r\nbemannat\r\nfaktan\r\navkommorna\r\nanslutits\r\nbeklädd\r\nantisemitiskt\r\nbastubad\r\narkivets\r\nbanditen\r\nfabeln\r\neroderat\r\ndelikatesser\r\ndammens\r\nbanar\r\nbagarn\r\ndugong\r\namuletten\r\nanvändarvänligt\r\nartistiskt\r\nbeskylld\r\nbokhandels\r\nberikat\r\nakuten\r\neftersträvat\r\nbokat\r\ndiskurser\r\nbilfärd\r\nberörts\r\nbranding\r\nbilparkering\r\navfyrat\r\ndedicerat\r\nbetänkligt\r\nadministratörs\r\nanatomen\r\ndivas\r\ndiagrams\r\neftersatta\r\ndetonationen\r\navpassad\r\nannexen\r\nbefarat\r\nfilantropisk\r\nargentinskt\r\nbrottningen\r\nbilvägar\r\navrättat" +
              "\r\ndeformerade\r\nboxers\r\nbeklätt\r\nekologism\r\nerforderligt\r\nbeskyllts\r\navverkats\r\navläggas\r\naktat\r\nantirasistisk\r\nelitlag\r\ndubbats\r\nbotanikens\r\nanalöppningen\r\nalper\r\nefterlämnar\r\nbekänt\r\ncentrums\r\nabnorme\r\ndilemman\r\nbovar\r\nbönerna\r\ndelens\r\nbökigt\r\ndeponerat\r\nbaskets\r\ndirektöversatt\r\ndivideras\r\nalmen\r\nbekostats\r\nbeten\r\nbörsens\r\nborrat\r\nbiljakt\r\navgränsats\r\nbakvägen\r\nbelystes\r\neterisk\r\ndialogerna\r\neremiter\r\nbadas\r\navträdda\r\nanalogin\r\nanförtrott\r\nforan\r\ndekaler\r\nalkemin\r\nbönens\r\ndelseger\r\naxelns\r\nankungen\r\ndirigeras\r\nelitens\r\nadministrations\r\navrättar\r\naptiten\r\nflammorna\r\narabens\r\nekologer\r\nantecknad\r\navskalat\r\nanslut\r\nautomaten\r\nandelarna\r\nfläkten\r\nalven\r\nblöjor\r\nanstalts\r\nbetänk\r\nbärgats\r\nbegärts\r\namorfa\r\nfestar\r\natomens\r\nbetal-tv\r\narresten\r\nbiträdd\r\n"
            };

            string wordsString = words[0];

            for (int index = 0; index < wordsString.Split("\r\n").Length; index++)
            {
                wordsSplit.Add(wordsString.Split("\r\n")[index]);
            }

            wordCount = wordsSplit.Count;
        }

        public int GetWordsCount()
        {
            return wordCount;
        }

        public string word(int index)
        {
            wordsSplit.ToArray();
            return wordsSplit[index];
        }
    }
}
